services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle19c.in.htwg-konstanz.de:1521/ora19c
      - SPRING_DATASOURCE_USERNAME=dbsys36
      - SPRING_DATASOURCE_PASSWORD=dbsysjohannes
