FROM node:22.3-alpine

ENV NODE_ENV=development

WORKDIR /app/frontend

COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm install

COPY frontend .
COPY .env ../.env

ENV DOTENV_PATH=../.env
EXPOSE 3000

CMD ["npm", "run", "dev"]
