FROM maven:3.8.6-openjdk-18-slim AS build
WORKDIR /app

COPY backend/pom.xml ./
COPY backend/src ./src
RUN mvn clean package shade:shade

FROM openjdk:20
WORKDIR /app

COPY --from=build /app/target/*.jar ./app.jar
COPY .env ./.env

ENV DOTENV_PATH=/.env
EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
